name: ccd-guide
channels:
  - astropy
  - conda-forge
dependencies:
- python=3.6
- astropy
- astroquery
- matplotlib<3
- ipython
- jupyter
- ipywidgets
- scipy >=1
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- wcsaxes
- ginga
- photutils
